apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-mxqt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-mxqt
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-mxqt
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-mxqt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-mxqt
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jncb-tenant/rhtap-demo-app/hacbs-test-project-mxqt@sha256:6c9e775d7afe94f720b6f8c28647f121d095364ff2f6e66bd1a4dd2fd35ee7d9
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
