apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-mxqt
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jncb-tenant/rhtap-demo-app/hacbs-test-project-mxqt@sha256:b2810e767b852c711d69c1ef186c3ea0460367216665bb2e08785dc742afc5f5
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
